# Generated by Django 5.0.6 on 2025-03-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_management', '0003_alter_commonmailinglist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonmailinglist',
            name='email',
            field=models.EmailField(default='test@gmail.com', editable=False, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
