# Generated by Django 5.0.6 on 2025-02-09 12:33

import core.shop_management.presentation.shop_management.models
import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inner_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('public_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=225)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('count_of_deals', models.PositiveBigIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inner_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('public_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=225)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('count_of_deals', models.PositiveBigIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='MultipleProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inner_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('public_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop/gallery_images/%y%m%d')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inner_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('public_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('size', models.CharField(max_length=225)),
                ('length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inner_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('public_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=225)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('description', models.TextField()),
                ('details', models.TextField()),
                ('image', models.ImageField(upload_to='shop/images/%y%m%d')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount', models.PositiveSmallIntegerField(default=0)),
                ('color', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('black', 'black'), ('white', 'white'), ('blue', 'blue')], default='black', max_length=225), default=core.shop_management.presentation.shop_management.models.default_colors, size=None)),
                ('in_stock', models.PositiveSmallIntegerField(default=1)),
                ('count_of_selled', models.PositiveSmallIntegerField(db_index=True, default=0, editable=False)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop_management.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop_management.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-time_created', 'name'],
            },
        ),
    ]
