# Generated by Django 5.0.6 on 2025-03-14 15:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('inner_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('public_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('quantity', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WishListOrderProduct',
            fields=[
                ('inner_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('public_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('color', models.CharField(blank=True, max_length=225, null=True)),
                ('qty', models.PositiveBigIntegerField(blank=True, default=1)),
            ],
            options={
                'verbose_name': "Wishlist's order-product",
                'verbose_name_plural': "Wishlist's order-products",
            },
        ),
    ]
