# Generated by Django 5.0.6 on 2025-02-09 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('review_management', '0001_initial'),
        ('shop_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrating',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_rating', to='shop_management.product'),
        ),
        migrations.AddField(
            model_name='review',
            name='product_rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='review_management.productrating'),
        ),
    ]
