# Generated by Django 5.0.6 on 2025-05-15 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_management', '0003_alter_wishlist_customer'),
        ('shop_management', '0003_alter_product_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistorderproduct',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_management.productsizes', to_field='public_uuid'),
        ),
    ]
