# Generated by Django 5.0.6 on 2025-05-27 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_management', '0004_alter_wishlistorderproduct_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='total_price',
        ),
    ]
